#!/usr/bin/env bash
# Display information about subdomains.

domain="${1}"
subdomain="${2}"

do_query () {
		query=$(dig "${1}.${2}" | grep -A1 'ANSWER SECTION' | tail -1)
}

get_data () {
	  data[0]=$(echo "${query}" | awk '{print $4}')
	  data[1]=$(echo "${query}" | awk '{print $5}')
}

print_msg () {
		echo "The subdomain ${1} is a ${2} record and points to ${3}"
}

if [ "${#}" -ge 2 ]
then
		do_query "${subdomain}" "${domain}"
		get_data "${query}"
		print_msg "${subdomain}" "${data[0]}" "${data[1]}"
else
		for sub in "www" "lb-01" "web-01" "web-02"
		do
				do_query "${sub}" "${domain}"
				get_data "${query}"
				print_msg "${sub}" "${data[0]}" "${data[1]}"
		done
fi
