#!/usr/bin/env bash
# Display information about subdomains.

domain="${1}"
subdomain="${2}"

get_data() {
	  data[0]=$(echo "${query}" | awk '{print $1}')
	  data[1]=$(echo "${query}" | awk '{print $4}')
	  data[2]=$(echo "${query}" | awk '{print $5}')
}

if [ "${#}" -ge 2 ];
then
		query=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION' | tail -1)
		get_data "${query}"
		echo "The subdomain ${subdomain} is a ${data[1]} record and points to ${data[2]}"
else
		def_subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in {0..3}
		do
				query=$(dig "${def_subdomains[sub]}.${1}" | grep -A1 'ANSWER SECTION' | tail -1)
				get_data "${query}"
				echo "The subdomain ${def_subdomains[sub]} is a ${data[1]} record and points to ${data[2]}"
		done
fi
