#!/usr/bin/env bash
# Configure Http Header Response
search="\troot \/var\/www\/html;"
new_string="\tadd_header X-Served-By $(hostname);"
sudo sed -i "s/${search}/${search}\n\n${new_string}/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
