#!/usr/bin/env bash
# Install and configure HAProxy
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt -y install haproxy=2.0.\*
server_1_info="4471-web-01 54.242.106.85:80"
server_2_info="4471-web-02 54.167.65.250:80"
frontend_conf="\nfrontend myfrontend\n\tbind 0.0.0.0:80\n\tdefault_backend myservers\n"
backend_conf="\nbackend myservers\n\tbalance roundrobin\n\tserver ${server_1_info} check\n\tserver ${server_2_info} check\n"
sudo service haproxy start
printf "${frontend_conf}" | sudo tee -a /etc/haproxy/haproxy.cfg
printf "${backend_conf}" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
